/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HealthPackagesRouteImport } from './routes/health-packages'
import { Route as HospitalAdminRouteImport } from './routes/hospital-admin'
import { Route as HospitalInvitationRouteImport } from './routes/hospital-invitation'
import { Route as HospitalsRouteImport } from './routes/hospitals'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as DoctorsSlugRouteImport } from './routes/doctors.$slug'
import { Route as HealthPackagesSlugRouteImport } from './routes/health-packages_.$slug'
import { Route as HospitalsSlugRouteImport } from './routes/hospitals_.$slug'
import { Route as BookDoctorSlugRouteImport } from './routes/book.doctor.$slug'
import { Route as BookPackageSlugRouteImport } from './routes/book.package.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthPackagesRoute = HealthPackagesRouteImport.update({
  id: '/health-packages',
  path: '/health-packages',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalAdminRoute = HospitalAdminRouteImport.update({
  id: '/hospital-admin',
  path: '/hospital-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalInvitationRoute = HospitalInvitationRouteImport.update({
  id: '/hospital-invitation',
  path: '/hospital-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsRoute = HospitalsRouteImport.update({
  id: '/hospitals',
  path: '/hospitals',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthPackagesSlugRoute = HealthPackagesSlugRouteImport.update({
  id: '/health-packages_/$slug',
  path: '/health-packages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const HospitalsSlugRoute = HospitalsSlugRouteImport.update({
  id: '/hospitals_/$slug',
  path: '/hospitals/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDoctorSlugRoute = BookDoctorSlugRouteImport.update({
  id: '/book/doctor/$slug',
  path: '/book/doctor/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BookPackageSlugRoute = BookPackageSlugRouteImport.update({
  id: '/book/package/$slug',
  path: '/book/package/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/health-packages': typeof HealthPackagesRoute
  '/hospital-admin': typeof HospitalAdminRoute
  '/hospital-invitation': typeof HospitalInvitationRoute
  '/hospitals': typeof HospitalsRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health-packages/$slug': typeof HealthPackagesSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/book/doctor/$slug': typeof BookDoctorSlugRoute
  '/book/package/$slug': typeof BookPackageSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/health-packages': typeof HealthPackagesRoute
  '/hospital-admin': typeof HospitalAdminRoute
  '/hospital-invitation': typeof HospitalInvitationRoute
  '/hospitals': typeof HospitalsRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health-packages/$slug': typeof HealthPackagesSlugRoute
  '/hospitals/$slug': typeof HospitalsSlugRoute
  '/book/doctor/$slug': typeof BookDoctorSlugRoute
  '/book/package/$slug': typeof BookPackageSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assistant': typeof AssistantRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/health-packages': typeof HealthPackagesRoute
  '/hospital-admin': typeof HospitalAdminRoute
  '/hospital-invitation': typeof HospitalInvitationRoute
  '/hospitals': typeof HospitalsRoute
  '/search': typeof SearchRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/health-packages_/$slug': typeof HealthPackagesSlugRoute
  '/hospitals_/$slug': typeof HospitalsSlugRoute
  '/book/doctor/$slug': typeof BookDoctorSlugRoute
  '/book/package/$slug': typeof BookPackageSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/health-packages'
    | '/hospital-admin'
    | '/hospital-invitation'
    | '/hospitals'
    | '/search'
    | '/subscriptions'
    | '/doctors/$slug'
    | '/health-packages/$slug'
    | '/hospitals/$slug'
    | '/book/doctor/$slug'
    | '/book/package/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/health-packages'
    | '/hospital-admin'
    | '/hospital-invitation'
    | '/hospitals'
    | '/search'
    | '/subscriptions'
    | '/doctors/$slug'
    | '/health-packages/$slug'
    | '/hospitals/$slug'
    | '/book/doctor/$slug'
    | '/book/package/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/auth'
    | '/dashboard'
    | '/health-packages'
    | '/hospital-admin'
    | '/hospital-invitation'
    | '/hospitals'
    | '/search'
    | '/subscriptions'
    | '/doctors/$slug'
    | '/health-packages_/$slug'
    | '/hospitals_/$slug'
    | '/book/doctor/$slug'
    | '/book/package/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AssistantRoute: typeof AssistantRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  HealthPackagesRoute: typeof HealthPackagesRoute
  HospitalAdminRoute: typeof HospitalAdminRoute
  HospitalInvitationRoute: typeof HospitalInvitationRoute
  HospitalsRoute: typeof HospitalsRoute
  SearchRoute: typeof SearchRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  HealthPackagesSlugRoute: typeof HealthPackagesSlugRoute
  HospitalsSlugRoute: typeof HospitalsSlugRoute
  BookDoctorSlugRoute: typeof BookDoctorSlugRoute
  BookPackageSlugRoute: typeof BookPackageSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-packages': {
      id: '/health-packages'
      path: '/health-packages'
      fullPath: '/health-packages'
      preLoaderRoute: typeof HealthPackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-admin': {
      id: '/hospital-admin'
      path: '/hospital-admin'
      fullPath: '/hospital-admin'
      preLoaderRoute: typeof HospitalAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospital-invitation': {
      id: '/hospital-invitation'
      path: '/hospital-invitation'
      fullPath: '/hospital-invitation'
      preLoaderRoute: typeof HospitalInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals': {
      id: '/hospitals'
      path: '/hospitals'
      fullPath: '/hospitals'
      preLoaderRoute: typeof HospitalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-packages_/$slug': {
      id: '/health-packages_/$slug'
      path: '/health-packages/$slug'
      fullPath: '/health-packages/$slug'
      preLoaderRoute: typeof HealthPackagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospitals_/$slug': {
      id: '/hospitals_/$slug'
      path: '/hospitals/$slug'
      fullPath: '/hospitals/$slug'
      preLoaderRoute: typeof HospitalsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/doctor/$slug': {
      id: '/book/doctor/$slug'
      path: '/book/doctor/$slug'
      fullPath: '/book/doctor/$slug'
      preLoaderRoute: typeof BookDoctorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/package/$slug': {
      id: '/book/package/$slug'
      path: '/book/package/$slug'
      fullPath: '/book/package/$slug'
      preLoaderRoute: typeof BookPackageSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AssistantRoute: AssistantRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  HealthPackagesRoute: HealthPackagesRoute,
  HospitalAdminRoute: HospitalAdminRoute,
  HospitalInvitationRoute: HospitalInvitationRoute,
  HospitalsRoute: HospitalsRoute,
  SearchRoute: SearchRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  HealthPackagesSlugRoute: HealthPackagesSlugRoute,
  HospitalsSlugRoute: HospitalsSlugRoute,
  BookDoctorSlugRoute: BookDoctorSlugRoute,
  BookPackageSlugRoute: BookPackageSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
